### ISSUE TITLE
求饱和度更低一点的颜色

### ISSUE THREAD

**Issue by FGBWZY** [rowthan/pagenote#101]
1. 跪求添加一些**饱和度更低，没那么刺眼**的眼色（类似于复古色系，莫兰迪色系这样子），目前的颜色除了那个蓝灰一样的颜色，其他颜色饱和度好高，眼睛要瞎掉了😹
2. 如果新添加颜色不太方便的话希望可以**调低透明度或者加入调整透明度的选项**，当然如果可以加入色板进行**自定义选色**那就更好了😺

**Comment by rowthan** [comment]
0.20.4 版本后支持自定义颜色
