### ISSUE TITLE
网页刷新之后标注的高亮会变成下划线形式 

### ISSUE THREAD

**Issue by iamqiz** [rowthan/pagenote#102]
如下图
刷新之前
![image](https://user-images.githubusercontent.com/48077521/134527193-9e7d2995-caa8-4d78-b1bd-6061c52471fb.png)
刷新之后
![image](https://user-images.githubusercontent.com/48077521/134527281-d3e63a38-4b28-44ce-9980-0c79845d574b.png)

**Comment by rowthan** [comment]
已修复
