### ISSUE TITLE
支付宝赞助后没有备注邮箱,使用订单号保存时总是提示 "verify error: null"

### ISSUE THREAD

**Issue by qstesiro** [rowthan/pagenote#104]
抱歉在issue区发此问题, 只是我在https://help.pagenote.cn/与https://pagenote.cn/pro-plan站点没有找到任何的客服联系方式,不知道开发人员能否解决:)

**Comment by rowthan** [comment]
把支付的截图，以及需要绑定的邮箱发到公众号吧，微信搜索： `pagenote` 。
https://help.pagenote.cn/about
