### ISSUE TITLE
【功能需求】复制功能能加个开关吗

### ISSUE THREAD

**Issue by Direct-A** [rowthan/pagenote#107]
复制功能有些时候并不需要，而且有时候会导致复制出来的不是选定的

**Comment by rowthan** [comment]
0.20.4 版本后默认已不添加复制功能，如可进入设置内添加、移除功能卡槽。

**Comment by Direct-A** [comment]
> 0.20.4 版本后默认已不添加复制功能，如可进入设置内添加、移除功能卡槽。

谢谢😁，开发菊苣辛苦了
