### ISSUE TITLE
希望可以增加禁用列表

### ISSUE THREAD

**Issue by roadom** [rowthan/pagenote#113]
浏览器目前越来越多的承载着管理，编辑等功能。
比如操作公司 oa 平台，在使用 web 端的协同云笔记功能时，pagenote 可能会成为障碍。

**Comment by rowthan** [comment]
目前支持`[赞助者](https://pagenote.cn/pro-plan)`使用该功能，其他用户待开放。

![image](https://user-images.githubusercontent.com/12638456/142523688-1fbf1e24-7c66-4774-96f9-399230fbc7be.png)

**Comment by XingyanMao** [comment]
![image](https://user-images.githubusercontent.com/50959195/230763713-46d76d88-c996-4407-9195-6e79b44d2add.png)
我这个版本咋没有了“禁用网页”的功能了呢

**Comment by rowthan** [comment]
> ![image](https://user-images.githubusercontent.com/50959195/230763713-46d76d88-c996-4407-9195-6e79b44d2add.png)
> 我这个版本咋没有了“禁用网页”的功能了呢
调整到此处->
![image](https://github.com/pagenote/pagenote/assets/12638456/0bc64cb9-e300-4b5d-a8ff-de34d88d6e85)
