### ISSUE TITLE
【订阅价格】订阅高级版本价格贵，有没有永久买断机制

### ISSUE THREAD

**Issue by CoolLiuzw** [rowthan/pagenote#115]
软件非常不错，期望支持永久买断机制，值得付费

**Comment by rowthan** [comment]
谢谢关注。

作为商品，相比其他软件来说，年付费的价格可能会略高。

现阶段还未将 PAGENOTE 作为产品来进行售卖，因为目前还未规模化、运营化运作，还不算一个成型、完善的产品。

我也是挤出业余时间来维护它。
目前支付页面中，对用户宣称为「赞助」，更多的是定义为打赏性质。也是对自己的一个激励，尽快完善它。

当下处于一个过渡阶段吧。会出买断制版本，在此之前用户赞助的支付金额可以用于抵扣买断制版本。所以现下赞助算是一种对PAGENOTE支持和提前众筹吧😀

**Comment by CoolLiuzw** [comment]
> 

谢谢您的回复，期待买断制版本。

也很赞同  在此之前用户赞助的支付金额可以用于抵扣买断制版本 的方式。

那可以提前赞助，谢谢。
