### ISSUE TITLE
标记所参照的网址希望能够通过设置来忽略某些参数

### ISSUE THREAD

**Issue by lilongthinker** [rowthan/pagenote#171]
比如 在网址 

https://help.aliyun.com/zh/ack/product-overview/kube-controller-manager?spm=a2c4g.11186623.0.0.6c547b71DKMaWl

设置的笔记
在spm的值发生变化，或者去掉spm的值（https://help.aliyun.com/zh/ack/product-overview/kube-controller-manager?）以后，就不再显示了。

希望能够让用户设置在某些域名下忽略某些参数来做为笔记所归属的网址，否则有些网站下内容很容易丢失

**Comment by rowthan** [comment]
same #153
