### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by CHENMING314159** [rowthan/pagenote#62]
我上网看文章的时候总喜欢鼠标左键选择一大段，但是当我选择一段文字的时候，你们显示出来的图标占了一大块，明显分散了我看文章的注意力。
所以我的建议是：
1.把图标显示做得小一点
2.图标要放在选择的区域偏下一点的地方
3.只显示一个图标就行，其它图标可以鼠标联动再弹出来，目前你们是一下显示四五个图标，太影响我看文章了

另外，产品不错，加油。

**Comment by rowthan** [comment]
建议收到。之后有更新后再在这里回复。

**Comment by rowthan** [comment]
0.13.3版本已调整 https://pagenote.cn/release
