### ISSUE TITLE
鼠标左键延时松手 随时实现 启用/禁用

### ISSUE THREAD

**Issue by ugotta** [rowthan/pagenote#66]
当前，通过按钮，或快捷键ctrl+shift+N来实现启用/禁用，且不是全局的。
鼠标选取文字，无论是否需要，立即弹出一排pagenote按钮，遮挡页面，建议可设置：

1. 鼠标左键框选文字到最后，继续按住100毫秒不松手，按钮不弹出，重新移动鼠标，立即松手则弹出；
2. 与上面相反，继续按住100毫秒才会弹出按钮，立即松手时不弹出，重新移动鼠标，已弹出按钮立即消失；

上面2种方式，几乎是不需要热键，就可以随时实现“启用/禁用”，倒是需要一组快捷键来切换上面2个方式，如果可能，在浏览器pagenote图标上点击或滚动鼠标中键来进行切换，而不是下拉列表再选择。顺便说一句，这个2个方式必须加上强烈建议几个字，考虑下；

另外可考虑减少动画和动画时长，使用越来越熟悉之后，需要跟上眼球和手速，特别是选取文字时；
搜索历史记录，如果可能，默认展示2排或可以下拉展示多排历史记录；

我关注这个很久了，之前是打不开pagenote网站，无法管理，直到后来可以访问了才开始使用，近期的改版越来好了，希望以后能继续给你有用的建议。

**Comment by rowthan** [comment]
感谢反馈。
1、随着用户越来越熟悉，原来看似友好的功能确实会变成一种困扰。
针对使用熟练的用户，在这里确实需要改进。提的这个建议很好，会考虑向这里去优化。另外之后按钮也会支持完全不出现，依赖右键的方式来完成目前所有的操作（目前右键，已经具备创建标记的功能了，可以试试）
2、动画这里，也确实会考虑关闭掉，或者以很难轻柔的方式，避免抢到过多的眼球，占用用户精力
3、搜索历史展示方式，旧版是支持的，可以支持1-4排排列方式，这个新版还没来得及迁移完，后面会支持上来。

反馈很中肯，谢谢。后续有进度，我会同步到这里。

**Comment by ugotta** [comment]
刚升级体验了右键标记，这个很基本的标配必须可以有，可以配合完全不出现浮动按钮。

不过我这个回复，其实是重新看了上面我最初的1.2.的建议，文字表达的不清楚，好像你没引起你的注意，我再重新整理一下：

鼠标左键滑动选文字时2种状态：
A滑动停止后立即松开左键。
B滑动停止后持续N毫秒，再松开左键。
以实现：
功能设置1：A按钮总是弹出，B按钮临时不弹出。
功能设置2：A按钮总是关闭，B按钮临时弹出。
两个功能可按场景切换着用

功能实现后特点，仅1次点击，无需多余的滑动和选择，无需右键和菜单，就能临时禁用/启用浮动按钮。如果技术上实现没问题，会很受欢迎

**Comment by rowthan** [comment]
hi 此功能已经在 0.15.6 版本中支持。详情见 [长按唤起](https://help.pagenote.cn/gong-neng-jie-shao/chang-an-huan-qi)
