### ISSUE TITLE
批注笔记无法修改+标签无法显示在管理界面

### ISSUE THREAD

**Issue by JamesBaoBao** [rowthan/pagenote#67]
1高亮的批注后无法进行修改，也无法再次添加批注，最好是一个高亮能添加好几条批注
2标签无法显示在管理界面，无法管理标签，最好是在管理页面能将批注根据标签分类

**Comment by rowthan** [comment]
1、目前批注没有条数的概念，可以任意修改编辑。可以认为只有一个
![image](https://user-images.githubusercontent.com/12638456/104143637-4980b300-53fb-11eb-92f8-9f7471ce3a99.png)
2、1）这个是一个遗留 近期加上。2）目前管理页能根据标签分组，目前支持：按时间分组、按域名分组、按标签分组

**Comment by rowthan** [comment]
2.1 已增加
