### ISSUE TITLE
Edge浏览器，在mac上做的笔记，在windows下无法同步

### ISSUE THREAD

**Issue by kevinstudio2003** [rowthan/pagenote#68]
使用微软的账号登录的

**Comment by rowthan** [comment]
edge 浏览器的登录与否跟 pagenote 没有关系哈。与浏览器登录账号没有任何联系。如果希望数据能在不同设备
、浏览器上同步，需要使用云盘功能。参考 https://www.yuque.com/docs/share/cc9e268d-04c6-4057-8b1e-f068f2bf60fb
