### ISSUE TITLE
【功能请求】希望在设置增加控件面板触发机制

### ISSUE THREAD

**Issue by ha-na-bi** [rowthan/pagenote#69]
平常浏览网页习惯会边看边划词，这样就会一直触发控件面板显示，导致浏览体验下降。

希望能在设置中增加控件面板显示的**触发机制**：

- [ ] 按住 <kbd>ctrl</kbd> / <kbd>alt</kbd> + 划词显示；
- [x] 永远不显示，但快捷键生效；
- [x] 划词即显示；（也就是当前版本默认的）

😄

**Comment by rowthan** [comment]
提议很好，会跟进处理

**Comment by rowthan** [comment]
hi 此功能已经在 0.15.6 版本中支持。详情见 [长按唤起](https://help.pagenote.cn/gong-neng-jie-shao/chang-an-huan-qi)
