### ISSUE TITLE
0.15.16 标记数量限制为30

### ISSUE THREAD

**Issue by WhyWhatHow** [rowthan/pagenote#84]
为什么要限制标记数量啊?
或者说,限制限制,能不能给的数量 多一些?

**Comment by rowthan** [comment]
> 为什么要限制标记数量啊?
> 或者说,限制限制,能不能给的数量 多一些?

默认30个，可以在设置页面进行调整：https://pagenote.cn/me#/setting/advance

**Comment by WhyWhatHow** [comment]
Sorry. i'm an idiot.
Thanks♪(･ω･)ﾉ
