### ISSUE TITLE
Do not output redundant information in the console

### ISSUE THREAD

**Issue by FreyaOne** [rowthan/pagenote#86]
After using this plug-in, when I click on the screen, the mouse click information will be output in the console. This is completely useless and affects viewing other messages.
![图片](https://user-images.githubusercontent.com/25958161/122342183-e204fb80-cf76-11eb-939d-f23eac716a35.png)

**Comment by FreyaOne** [comment]
environment：firefox 89.0

**Comment by rowthan** [comment]
Got it, it will be resolve in next version.

**Comment by FreyaOne** [comment]
Thanks sincerely, the tool is very useful and beautiful

**Comment by rowthan** [comment]
resolved in the version of [0.16.8](https://addons.mozilla.org/zh-CN/firefox/addon/page-note/)
