### ISSUE TITLE
云盘,即webdav一直验证失败,无法上传

### ISSUE THREAD

**Issue by lin0kin** [rowthan/pagenote#88]
使用了nextcloud和坚果云,都无法成功上传

**Comment by rowthan** [comment]
加密串有设置吗？设置加密串后再试下呢？如果还不行 可以加入用户群（微信公众号 pagenote）排查

**Comment by rowthan** [comment]
> 使用了nextcloud和坚果云,都无法成功上传

已确定问题： 没有配置数据存储路径。
解决方式： 配置存储路径即可（之前无法自定义，现已开放配置 ctrl+shift+R 刷新页面后使用即可），如 `/pagenote`

**Comment by lin0kin** [comment]
> > 使用了nextcloud和坚果云,都无法成功上传
> 
> 已确定问题： 没有配置数据存储路径。
> 解决方式： 配置存储路径即可（之前无法自定义，现已开放配置 ctrl+shift+R 刷新页面后使用即可），如 `/pagenote`

原来如此, 谢谢
