### ISSUE TITLE
Unable to save markdown

### ISSUE THREAD

**Issue by Cip4a** [rowthan/pagenote#90]
Hi rowthan
With the latest version of Pagenote 0.16.7 I can't save notes in markdown format.
Firefox 55
mac osx 10.11
page notes 0.16.7

**Comment by rowthan** [comment]
> Hi rowthan
> With the latest version of Pagenote 0.16.7 I can't save notes in markdown format.
> Firefox 55
> mac osx 10.11
> page notes 0.16.7

update the export function today. how about have a one more try?
![image](https://user-images.githubusercontent.com/12638456/124684997-f8153480-df02-11eb-9a4f-92b00316e3a9.png)

The first icon for exporting data to clipboard and another one for exporting data as a `.markdown` file
