### ISSUE TITLE
需要 自定义白名单和黑名单 或 默认不开启

### ISSUE THREAD

**Issue by ChuGary** [rowthan/pagenote#92]
有的网站真的用不上，我是只在部分论文期刊网站使用的用户。
另外我还有用一个翻译的插件，经常会重叠到一起。

![截图_20210216100208](https://user-images.githubusercontent.com/60617720/125960294-14e61817-1535-41eb-ab28-73c6c6393b7a.png)

所以真的希望能给一个自定义白名单和黑名单的功能，而且不是只针对一个固定的网址，而是同一个网址前缀的一系列网址。

球球了，真的很需要这个功能！

**Comment by rowthan** [comment]
针对你的问题，可以试试使用「延迟功能」是否能满足你需求：
该功能能够确保在你需要的时候才出现对应的操作面板，避免和其他插件产生影响。

https://help.pagenote.cn/guide/chang-an-huan-qi

**Comment by iamqiz** [comment]
如果使用chrome系列浏览器 有两种方法:如下图
![image](https://user-images.githubusercontent.com/48077521/134528032-59ac9172-0100-4d82-8c55-7d662293649c.png)
第一种,在所有网站上都生效,但必须先点击插件图标
第二种,添加当前网站为允许插件生效的网站列表里
第二种还可以在插件的详情页里设置,如下图:
![image](https://user-images.githubusercontent.com/48077521/134528539-89307381-f800-4508-a869-b88721362908.png)

**Comment by rowthan** [comment]
0.20.4 版本后支持 「在此网站禁用」配置。
