### ISSUE TITLE
网页边缘标记文字，工具栏长度超出范围

### ISSUE THREAD

**Issue by SongX64** [rowthan/pagenote#96]
用的Edge浏览器，在网页边缘标记文字，鼠标指上去的时候，工具栏长度超出范围。虽然说底部会出现一个横向滚动条。。但是去拖动的时候他就消失了。

比如[这个网页](https://tech.meituan.com/2017/12/29/jvm-optimize.html)，标记一行最右面的少量字的时候就会出现这个问题。

示例：
![示例](https://gitee.com/songx86/SongPicBed/raw/master/img/QQ%E6%88%AA%E5%9B%BE20210806184816.jpg)

**Comment by rowthan** [comment]
新版0.18.0已优化 ，可以再看看
